---
# tasks file for vector-role
# ======== Скачиваем rpm (RedHat) пакета vector для установки=======
- name: Get Vector distrib | CentOS
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.{{ ansible_architecture }}.rpm"
    dest: "./vector-{{ vector_version }}.rpm"
    mode: 0644
  when: ansible_facts.distribution == "CentOS"
# ======== Скачиваем apt (Debian) пакет vector для установки=======
- name: Get Vector distrib | Ubuntu
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_amd64.deb"
    dest: "./vector_{{ vector_version }}.deb"
    mode: 0644
  when: ansible_facts.distribution == "Ubuntu"
# ===========Устанавливаем rpm (RedHat) пакет vector=========
- name: Install Vector packages | CentOS
  become: true
  ansible.builtin.yum:
    name: "vector-{{ vector_version }}.rpm"
    state: present
  notify: Start Vector service
  when: ansible_facts.distribution == "CentOS"
# ===========Устанавливаем apt (Debian) пакет vector=========
- name: Install Vector packages | Ubuntu
  become: true
  ansible.builtin.apt:
    deb: "vector_{{ vector_version }}.deb"
  notify: Start Vector service
  when: ansible_facts.distribution == "Ubuntu"
# ==========Создание файла конфигурации для vector========
- name: Deploy config Vector
  ansible.builtin.template:
    src: vector.j2
    dest: "{{ vector_config_path }}"
    mode: 0644
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    validate: vector validate --no-environment --config-yaml %s
  become: true
  notify: Start Vector service
# ========Создание каталога для sources local_logs==========
- name: Creates directory
  become: true
  file:
    path: /var/lib/vector/local_logs
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: 0644
- name: Create systemd unit Vector
  become: true
  template:
    src: vector.service.j2
    dest: /etc/systemd/system/vector.service
    mode: 0644
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
  notify: Start Vector service
