---
# handlers file for vector-role
# handlers для старта/рестарта сервиса Vector
- name: Start Vector service
  become: true
  ansible.builtin.systemd:
    name: vector
    state: restarted
    enabled: true
  when: ansible_connection == 'docker'
